import "./globals.css";
import { Geist, Geist_Mono, Lily_Script_One } from "next/font/google";
import { Ancizar_Serif, Inter, Instrument_Serif } from "next/font/google";
import SmoothScrollProvider from "./components/SmoothScrollProvider";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

const ancizarSerif = Ancizar_Serif({
  subsets: ["latin"],
  variable: "--font-ancizar-serif",
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
});

const instrumentSerif = Instrument_Serif({
  weight:"400",
  subsets: ["latin"],
  variable: "--font-instrument-serif",
});

const lilyScriptOne = Lily_Script_One({
  weight:"400",
  subsets:["latin"],
  variable:"--font-lily-script-one"

  
})

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      className={`${geistSans.variable} ${geistMono.variable} ${instrumentSerif.variable} ${inter.variable} ${ancizarSerif.variable}     ${lilyScriptOne.variable} h-full antialiased`}
    >
     <body className="antialiased bg-[#050505]">
        <SmoothScrollProvider>{children}</SmoothScrollProvider>
      </body>
    </html>
  );
}
